<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0</TargetFrameworks>

    <ApplicationIcon>..\NzbDrone.Host\Readarr.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="!$(RuntimeIdentifier.StartsWith('win'))">
    <AssemblyName>Readarr</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Host\Readarr.Host.csproj" />
  </ItemGroup>
  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <ProjectReference Include="..\NzbDrone.Windows\Readarr.Windows.csproj" />
  </ItemGroup>
  <ItemGroup Condition="!$([MSBuild]::IsOSPlatform('Windows'))">
    <ProjectReference Include="..\NzbDrone.Mono\Readarr.Mono.csproj" />
  </ItemGroup>
</Project>
