// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'rootFolderField': string;
  'rootFolderHelpText': string;
}
export const cssExports: CssExports;
export default cssExports;
