// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clearLookupButton': string;
  'helpText': string;
  'message': string;
  'noResults': string;
  'searchContainer': string;
  'searchIconContainer': string;
  'searchInput': string;
  'searchLoadingIndicator': string;
  'searchLoadingRipple': string;
  'searchResults': string;
  'searchScopeSelect': string;
}
export const cssExports: CssExports;
export default cssExports;
