// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'breadcrumb': string;
  'description': string;
  'descriptionBlock': string;
  'detailGrid': string;
  'detailItem': string;
  'detailLink': string;
  'heroColumn': string;
  'heroImage': string;
  'heroPlaceholder': string;
  'heroPlaceholderGraphic': string;
  'issueGraphic': string;
  'issueGraphicImage': string;
  'issueGraphicPlaceholder': string;
  'issuesTable': string;
  'overviewCard': string;
  'pageContent': string;
  'pathValue': string;
  'statPill': string;
  'statRow': string;
  'subtitle': string;
  'summaryColumn': string;
  'thumbnailColumn': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
