// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cover': string;
  'coverContainer': string;
  'coverPlaceholder': string;
  'detailsLabel': string;
  'detailsLabels': string;
  'externalLink': string;
  'header': string;
  'headerContent': string;
  'info': string;
  'labelText': string;
  'monitorToggleButton': string;
  'overview': string;
  'subtitle': string;
  'title': string;
  'titleBlock': string;
  'titleContainer': string;
  'titleRow': string;
  'toggleMonitoredContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
