// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentContainer': string;
  'emptyState': string;
  'innerContentBody': string;
  'issueGraphic': string;
  'issueGraphicImage': string;
  'issueGraphicPlaceholder': string;
  'issuesTable': string;
  'sectionTitle': string;
  'summaryCard': string;
  'summaryGrid': string;
  'summaryLabel': string;
  'summaryValue': string;
  'tableSection': string;
  'thumbnailColumn': string;
}
export const cssExports: CssExports;
export default cssExports;
