// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentBody': string;
  'contentBodyContainer': string;
  'errorMessage': string;
  'filters': string;
  'innerContentBody': string;
  'pageContentBodyWrapper': string;
  'pageIndicator': string;
  'pagination': string;
  'selectInput': string;
  'table': string;
  'tableLink': string;
  'tableWrapper': string;
  'textInput': string;
}
export const cssExports: CssExports;
export default cssExports;
