// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentBody': string;
  'contentBodyContainer': string;
  'errorMessage': string;
  'filtersPanel': string;
  'innerContentBody': string;
  'pageContentBodyWrapper': string;
  'resultsSummary': string;
  'selectInput': string;
  'textInput': string;
}
export const cssExports: CssExports;
export default cssExports;
