// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cover': string;
  'coverImage': string;
  'coverPlaceholder': string;
  'coverText': string;
}
export const cssExports: CssExports;
export default cssExports;
