// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'info': string;
  'monitored': string;
  'monitoredIcon': string;
  'publisher': string;
  'stat': string;
  'statLabel': string;
  'statValue': string;
  'stats': string;
  'title': string;
  'titleRow': string;
  'unmonitored': string;
}
export const cssExports: CssExports;
export default cssExports;
