// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'info': string;
  'meta': string;
  'monitored': string;
  'publisher': string;
  'status': string;
  'title': string;
  'unmonitored': string;
}
export const cssExports: CssExports;
export default cssExports;
